services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bank-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
    restart: always


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bank-frontend
    ports:
    - "3000:3000"
    depends_on:
      - backend
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:


