services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bank-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongodb
      - redis
    restart: always

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: bank-frontend
  #   ports:
  #   - "3000:3000"
  #   depends_on:
  #     - backend
  #   restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27016:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo_data:
  redis-data:


